Implement snake game
Thomaltarix/Arrrrrcade pull request #61
Opened 2024-03-30 15:53 UTC by Thomaltarix

I finished the Snake Game completely.
To see details, check this issue:
- #39

2024-03-30 16:31 UTC, mathieurobert1 requested changes
Some changes to makes but a really good code

2024-03-30 16:31 UTC, mathieurobert1 commented on src/Core/Core.cpp
> +#include "IGame.hpp"
IGame is already in the Core.hpp

2024-03-30 16:31 UTC, mathieurobert1 commented on src/Games/AGame.hpp
> +            private:
Protected instead of Private in an Abstract class ?

2024-03-30 16:31 UTC, mathieurobert1 commented on src/Games/APlayer.cpp
> +int Arcade::APlayer::die()
why int function if the return is always -1 ?

2024-03-30 16:31 UTC, mathieurobert1 commented on src/Games/APlayer.hpp
> +        private:
it's not protected for an Abstract ?

2024-03-30 16:31 UTC, mathieurobert1 commented on src/Games/SNAKE/Snake.cpp
> +void Arcade::SnakeGame::initMap(int width, int height)
The map initialization is not good, look at the Centipede map creation to create the map

2024-03-30 16:32 UTC, Thomaltarix commented on src/Core/Core.cpp
> +#include "IGame.hpp"
Done

2024-03-30 16:34 UTC, Thomaltarix commented on src/Games/AGame.hpp
> +            private:
Yes, you're right !

2024-03-30 16:34 UTC, Thomaltarix commented on src/Games/APlayer.hpp
> +        private:
Same as above, you're right here too

2024-03-30 16:38 UTC, Thomaltarix commented on src/Games/APlayer.cpp
> +int Arcade::APlayer::die()
Good request !

2024-03-30 16:39 UTC, Thomaltarix commented on src/Games/SNAKE/Snake.cpp
> +void Arcade::SnakeGame::initMap(int width, int height)
I think we are just reversing the x and y for our map, so it causes nothing

2024-03-31 16:20 UTC, mathieurobert1 approved these changes
Seems perfect :+1:

2024-03-31 20:12 UTC, merged